image: maven:3.2-jdk-7

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script: 
    - cd zh-l16
    - mvn install -B
  artifacts:
    paths:
     - zh-l16/target/
     
deploy to test:
    when: manual
    environment: test
    stage: test
    script: echo "DEPLOYING TO TEST"