image: maven:3.5-jdk-8

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script: 
    - cd zh-l16
    - mvn install -B
  artifacts:
    paths:
     - zh-l16/target/
     
deploy to test1:
    when: manual
    environment: test1
    stage: test
    script: echo "DEPLOYING TO TEST1"
    
deploy to test2:
    when: manual
    environment: test2
    stage: test
    script: echo "DEPLOYING TO TEST2"